version: '3'
services:

  php:
    build:
      args:
        user: syam
        uid: 1000
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./:/var/www/
      - $HOME/.composer/:$HOME/.composer/
    environment:
      - "DB_HOST=mysql"
      - "DB_DATABASE=forsa"
      - "DB_USERNAME=forsa"
      - "DB_PASSWORD=forsa"
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"
    networks:
      - service-network

  nginx:
    image: nginx:alpine
    container_name: web-server
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d/
    networks:
      - service-network

  mysql:
    image: mariadb:10.5.8
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=forsa"
      - "MYSQL_DATABASE=forsa"
      - "MYSQL_USER=forsa"
      - "MYSQL_PASSWORD=forsa"
    ports:
        - "3307:3306"
    networks:
      - service-network

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8001:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - UPLOAD_LIMIT=100000000
    networks:
      - service-network
  redis:
    image: redis:4.0-alpine
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    networks:
      - service-network

volumes:
  mysqldata:

networks:
  service-network:
    driver: bridge
